apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    #path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/pv01
    path: /mnt/sda1/hostpath_pv/pv001

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    #path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/pv01
    path: /mnt/sda1/hostpath_pv/pv002

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-pv01"
  namespace: test001
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "3Gi"
  volumeName: "pv01"
  #selector:
  #  name: "pv01"

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-pv02"
  namespace: test001
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "3Gi"
  volumeName: "pv02"
  #selector:
  #  name: "pv02"