apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "webwork.fullname" . }}
  labels:
    app: {{ template "webwork.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "webwork.fullname" . }}
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "webwork.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MARIADB_HOST
          value: {{ template "webwork.mariadb.fullname" . }}
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "webwork.mariadb.fullname" . }}
              key: mariadb-root-password
        - name: webwork_USERNAME
          value: {{ default "" .Values.webworkUsername | quote }}
        - name: webwork_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "webwork.fullname" . }}
              key: webwork-password
        - name: webwork_EMAIL
          value: {{ default "" .Values.webworkEmail | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "webwork.fullname" . }}
              key: smtp-password
        - name: SMTP_PROTOCOL
          value: {{ default "" .Values.smtpProtocol | quote }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /login/index.php
            port: http
          initialDelaySeconds: 180
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /login/index.php
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: webwork-data
          mountPath: /bitnami
      volumes:
      - name: webwork-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "webwork.webwork.fullname" . ) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
