apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webwork.fullname" . }}
  labels:
    app: {{ template "webwork.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.webworkPassword }}
  webwork-password: {{ default "" .Values.webworkPassword | b64enc | quote }}
  {{ else }}
  webwork-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
